#!/usr/bin/env python3
"""Add a new book to the Prosora blog.

Generates the PDF (if missing) and (re)builds the book DATA arrays in
index.html and books.html from the local pdf/ folder, so pagination and
"first 6 on home" stay correct automatically. No hardcoded cards.

Usage:
  python3 add_book.py "The Psychology of Money" "Morgan Housel"
"""
import sys, subprocess, re
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
VENV = BASE / ".venv" / "bin" / "activate"


def _books():
    """Scan pdf/ for book PDFs, return list of (title, author, file)."""
    out = []
    for pdf in sorted(BASE.glob("pdf/*.pdf")):
        fn = pdf.stem  # e.g. The_4-Hour_Workweek
        # find author: best-effort from known mapping; fallback blank
        out.append(fn)
    return out


def _author_for(title):
    # simple known-author map (extend as needed)
    m = {
        "Atomic_Habits": "James Clear",
        "The_Psychology_of_Money": "Morgan Housel",
        "Rich_Dad_Poor_Dad": "Robert Kiyosaki",
        "The_4-Hour_Workweek": "Timothy Ferriss",
        "The_Simple_Path_to_Wealth": "JL Collins",
        "The_Psychology_of_Human_Misjudgment": "Charlie Munger",
        "The_E-Myth_Revisited": "Michael Gerber",
        "The_Total_Money_Makeover": "Dave Ramsey",
        "Think_and_Grow_Rich": "Napoleon Hill",
        "The_Millionaire_Next_Door": "Thomas J. Stanley",
        "The_Wisdom_of_Finance": "Mihir Desai",
        "Devil_Take_the_Hindmost": "Edward Chancellor",
        "The_Only_Three_Questions_That_Count": "Ken Fisher",
        "Money_Mischief": "Milton Friedman",
        "The_House_of_Morgan": "Ron Chernow",
        "Tap_Dancing_to_Work": "Carol Loomis",
        "The_Ten_Roads_to_Riches": "Ken Fisher",
        "The_Interpretation_of_Financial_Statements": "Benjamin Graham",
        "The_Investment_Checklist": "Michael Shearn",
        "Financial_Shenanigans": "Howard Schilit",
        "More_Money_Than_God": "Sebastian Mallaby",
        "The_Great_Crash_1929": "John Kenneth Galbraith",
        "The_Ascent_of_Money": "Niall Ferguson",
        "Den_of_Thieves": "James B. Stewart",
        "Barbarians_at_the_Gate": "Bryan Burrough",
        "When_Genius_Failed": "Roger Lowenstein",
        "The_Clash_of_the_Cultures": "John C. Bogle",
        "The_Money_Game": "George Goodman",
        "Where_Are_the_Customers'_Yachts?": "Fred Schwed",
        "The_Zurich_Axioms": "Max Gunther",
        "The_Phoenix_Project": "Gene Kim",
        "Too_Big_to_Fail": "Andrew Ross Sorkin",
        "The_Smartest_Guys_in_the_Room": "Bethany McLean",
        "The_New_New_Thing": "Michael Lewis",
        "Boomerang": "Michael Lewis",
        "The_Blind_Side": "Michael Lewis",
        "The_Undoing_Project": "Michael Lewis",
        "Nonviolent_Communication": "Marshall Rosenberg",
        "Attached": "Amir Levine",
        "The_Body_Keeps_the_Score": "Bessel van der Kolk",
        "The_Four_Tendencies": "Gretchen Rubin",
        "The_Paradox_of_Choice": "Barry Schwartz",
        "Tax-Free_Wealth": "Tom Wheelwright",
        "The_Bed_of_Procrustes": "Nassim Nicholas Taleb",
        "Enough": "John C. Bogle",
        "How_to_Make_Money_in_Stocks": "William J. O'Neil",
        "Value_Proposition_Design": "Alexander Osterwalder",
        "Business_Model_Generation": "Alexander Osterwalder",
        "The_Four_Steps_to_the_Epiphany": "Steve Blank",
        "A_Guide_to_the_Good_Life": "William B. Irvine",
        "Happier": "Tal Ben-Shahar",
        "Meatball_Sundae": "Seth Godin",
        "The_E-Myth_Mastery": "Michael Gerber",
        "The_Icarus_Deception": "Seth Godin",
        "The_Charisma_Myth": "Olivia Fox Cabane",
        "The_Miracle_of_Mindfulness": "Thich Nhat Hanh",
        "10%_Happier": "Dan Harris",
        "The_Happiness_Equation": "Neil Pasricha",
        "Designing_Your_Life": "Bill Burnett & Dave Evans",
        "Do_the_Work": "Steven Pressfield",
        "The_Practice": "Seth Godin",
        "The_First_20_Hours": "Josh Kaufman",
        "The_Investor's_Paradox": "Michael Pompian",
        "Millionaire_Teacher": "Andrew Hallam",
        "The_Misbehavior_of_Markets": "Benoit Mandelbrot",
        "Irrational_Exuberance": "Robert Shiller",
        "Fortune's_Formula": "William Poundstone",
        "Against_the_Gods": "Peter L. Bernstein",
        "The_Drunkard's_Walk": "Leonard Mlodinow",
        "The_Outsiders": "William Thorndike",
        "A_Million_Bucks_by_30": "Alan Corey",
        "The_Hedge_Fund_Mirage": "Simon Lack",
        "The_Bond_Book": "Annette Thau",
        "The_Single_Best_Investment": "Lowell Miller",
        "The_Investors_Manifesto": "William Bernstein",
        "Winning_the_Losers_Game": "Charles Ellis",
        "Unconventional_Success": "David Swensen",
        "Flash_Boys": "Michael Lewis",
        "Moneyball": "Michael Lewis",
        "Thinking_Fast_and_Slow": "Daniel Kahneman",
        "Quiet": "Susan Cain",
        "The_Startup_Owners_Manual": "Steve Blank",
        "The_Innovators_Dilemma": "Clayton Christensen",
        "The_Dao_of_Capital": "Mark Spitznagel",
        "The_Wealthy_Gardener": "John Soforic",
        "You_Are_a_Badass": "Jen Sincero",
        "Poor_Charlies_Almanack": "Charlie Munger",
        "The_Gap_and_The_Gain": "Dan Sullivan",
        "The_Cashflow_Quadrant": "Robert Kiyosaki",
        "The_Bogleheads_Guide_to_Investing": "Taylor Larimore",
        "Keep_Going": "Austin Kleon",
        "Rising_Strong": "Brene Brown",
        "The_Confidence_Code": "Katty Kay",
        "The_Long_Game": "Dorie Clark",
        "Slow_Productivity": "Cal Newport",
        "A_World_Without_Email": "Cal Newport",
        "Talent": "Tyler Cowen",
        "The_Sports_Gene": "David Epstein",
        "The_Mastery_of_Love": "Don Miguel Ruiz",
        "The_Fifth_Agreement": "Don Miguel Ruiz",
        "Work_Rules": "Laszlo Bock",
        "Thanks_for_the_Feedback": "Douglas Stone",
        "Difficult_Conversations": "Douglas Stone",
        "The_Power_of_Regret": "Daniel H. Pink",
        "No_Rules_Rules": "Reed Hastings",
        "Relentless": "Tim S. Grover",
        "Make_It_Stick": "Peter C. Brown",
        "The_5_Types_of_Wealth": "Sahil Bloom",
        "The_Algebra_of_Wealth": "Scott Galloway",
        "Same_as_Ever": "Morgan Housel",
        "The_Tao_of_Warren_Buffett": "Mary Buffett",
        "The_New_Buffettology": "Mary Buffett",
        "Buffettology": "Mary Buffett",
        "The_Warren_Buffett_Portfolio": "Robert G. Hagstrom",
        "Reminiscences_of_a_Stock_Operator": "Edwin Lefevre",
        "Trading_in_the_Zone": "Mark Douglas",
        "The_Complete_Turtle_Trader": "Michael Covel",
        "Trend_Following": "Michael Covel",
        "Market_Wizards": "Jack D. Schwager",
        "The_Five_Rules_for_Successful_Stock_Investing": "Pat Dorsey",
        "The_Little_Book_of_Valuation": "Aswath Damodaran",
        "Seeking_Wisdom": "Peter Bevelin",
        "The_Bogleheads'_Guide_to_the_Three-Fund_Portfolio": "Taylor Larimore",
        "Your_Money_and_Your_Brain": "Jason Zweig",
        "The_Second_Mountain": "David Brooks",
        "The_Road_to_Character": "David Brooks",
        "The_Social_Animal": "David Brooks",
        "The_Righteous_Mind": "Jonathan Haidt",
        "The_Next_Millionaire_Next_Door": "Sarah Stanley Fallaw",
        "The_Millionaire_Women_Next_Door": "Thomas J. Stanley",
        "Flow": "Mihaly Csikszentmihalyi",
        "The_Power_of_Positive_Thinking": "Norman Vincent Peale",
        "Remote": "Jason Fried",
        "Team_of_Teams": "Stanley McChrystal",
        "The_Coaching_Habit": "Michael Bungay Stanier",
        "The_Innovator's_Solution": "Clayton M. Christensen",
        "The_Shallows": "Nicholas Carr",
        "Stumbling_on_Happiness": "Daniel Gilbert",
        "The_Gifts_of_Imperfection": "Brené Brown",
        "Braving_the_Wilderness": "Brené Brown",
        "The_Creative_Act": "Rick Rubin",
        "The_50th_Law": "Robert Greene",
        "The_Smart_Money_Woman": "Arese Ugwu",
        "The_One-Page_Financial_Plan": "Carl Richards",
        "Rich_Dad's_Who_Took_My_Money?": "Robert Kiyosaki",
        "The_Power_of_Intention": "Wayne W. Dyer",
        "The_8th_Habit": "Stephen R. Covey",
        "The_Alchemist": "Paulo Coelho",
        "The_5_Love_Languages": "Gary Chapman",
        "First_Things_First": "Stephen R. Covey",
        "Man's_Search_for_Meaning": "Viktor E. Frankl",
        "The_Four_Agreements": "Don Miguel Ruiz",
        "Who_Will_Cry_When_You_Die?": "Robin Sharma",
        "Courage_Is_Calling": "Ryan Holiday",
        "Lives_of_the_Stoics": "Ryan Holiday",
        "Outwitting_the_Devil": "Napoleon Hill",
        "Success_Through_a_Positive_Mental_Attitude": "Napoleon Hill",
        "The_Go-Giver": "Bob Burg",
        "The_Success_Principles": "Jack Canfield",
        "Financial_Peace_Revisited": "Dave Ramsey",
        "Learn_to_Earn": "Peter Lynch",
        "Beating_the_Street": "Peter Lynch",
        "Buffett:_The_Making_of_an_American_Capitalist": "Roger Lowenstein",
        "Stop_Acting_Rich": "Thomas J. Stanley",
        "Tribe_of_Mentors": "Timothy Ferriss",
        "How_to_Stop_Worrying_and_Start_Living": "Dale Carnegie",
        "The_Money_Book_for_the_Young,_Fabulous_&_Broke": "Suze Orman",
        "Concentrated_Investing": "Allen Benello",
        "Deep_Value": "Tobias Carlisle",
        "The_Investor's_Manifesto": "William J. Bernstein",
        "The_Little_Book_of_Value_Investing": "Christopher Browne",
        "Marketing_Made_Simple": "Donald Miller",
        "Hyperfocus": "Chris Bailey",
        "The_Outward_Mindset": "The Arbinger Institute",
        "The_Power_of_Less": "Leo Babauta",
        "All_Marketers_Are_Liars": "Seth Godin",
        "Running_Lean": "Ash Maurya",
        "The_Willpower_Instinct": "Kelly McGonigal",
        "They_Ask_You_Answer": "Marcus Sheridan",
        "The_Advantage": "Patrick Lencioni",
        "The_Startup_Owner's_Manual": "Steve Blank",
        "Indistractable": "Nir Eyal",
        "Tiny_Habits": "B.J. Fogg",
        "The_1-Page_Marketing_Plan": "Allan Dib",
        "The_Toyota_Way": "Jeffrey Liker",
        "Turn_the_Ship_Around!": "L. David Marquet",
        "This_Is_Marketing": "Seth Godin",
        "The_Lean_Product_Playbook": "Dan Olsen",
        "The_Founder's_Dilemmas": "Noam Wasserman",
        "High_Growth_Handbook": "Elad Gil",
        "Winning": "Jack Welch",
        "The_Score_Takes_Care_of_Itself": "Bill Walsh",
        "The_Culture_Map": "Erin Meyer",
        "Radical_Candor": "Kim Scott",
        "Multipliers": "Liz Wiseman",
        "The_Power_of_Full_Engagement": "Jim Loehr",
        "The_Happiness_Advantage": "Shawn Achor",
        "The_Art_of_Possibility": "Rosamund Stone Zander",
        "Venture_Deals": "Brad Feld",
        "Founders_at_Work": "Jessica Livingston",
        "The_21_Irrefutable_Laws_of_Leadership": "John C. Maxwell",
        "Leadership_and_Self-Deception": "The Arbinger Institute",
        "The_Five_Dysfunctions_of_a_Team": "Patrick Lencioni",
        "Predictable_Revenue": "Aaron Ross",
        "The_Challenger_Sale": "Matthew Dixon",
        "The_Art_of_the_Start": "Guy Kawasaki",
        "The_One_Minute_Manager": "Ken Blanchard",
        "Blitzscaling": "Reid Hoffman",
        "The_Sales_Bible": "Jeffrey Gitomer",
        "Jab,_Jab,_Jab,_Right_Hook": "Gary Vaynerchuk",
        "Crushing_It!": "Gary Vaynerchuk",
        "The_Cold_Start_Problem": "Andrew Chen",
        "Obviously_Awesome": "April Dunford",
        "Playing_to_Win": "A.G. Lafley",
        "Competing_Against_Luck": "Clayton M. Christensen",
        "The_Goal": "Eliyahu M. Goldratt",
        "Only_the_Paranoid_Survive": "Andrew S. Grove",
        "High_Output_Management": "Andrew S. Grove",
        "The_Great_CEO_Within": "Matt Mochary",
        "Key_Person_of_Influence": "Daniel Priestley",
        "Oversubscribed": "Daniel Priestley",
        "Traffic_Secrets": "Russell Brunson",
        "Dotcom_Secrets": "Russell Brunson",
        "Expert_Secrets": "Russell Brunson",
        "The_Ultimate_Sales_Machine": "Chet Holmes",
        "Building_a_StoryBrand": "Donald Miller",
        "Little_Red_Book_of_Selling": "Jeffrey Gitomer",
        "The_Lean_Six_Sigma_Pocket_Toolbook": "Michael L. George",
        "The_Sales_Acceleration_Formula": "Mark Roberge",
        "Amp_It_Up": "Frank Slootman",
        "Trillion_Dollar_Coach": "Eric Schmidt",
        "Broke_Millennial": "Erin Lowry",
        "The_White_Coat_Investor": "James M. Dahle",
        "Just_Keep_Buying": "Nick Maggiulli",
        "Die_With_Zero": "Bill Perkins",
        "Quit_Like_a_Millionaire": "Kristy Shen",
        "Financial_Freedom": "Grant Sabatier",
        "The_Millionaire_Real_Estate_Investor": "Gary Keller",
        "Getting_to_Yes": "Roger Fisher",
        "Eat_That_Frog": "Brian Tracy",
        "The_12_Week_Year": "Brian Moran",
        "Company_of_One": "Paul Jarvis",
        "Rework": "Jason Fried",
        "The_Mom_Test": "Rob Fitzpatrick",
        "Good_Strategy_Bad_Strategy": "Richard Rumelt",
        "Blue_Ocean_Strategy": "W. Chan Kim",
        "Scaling_Up": "Verne Harnish",
        "Traction": "Gino Wickman",
        "The_Geometry_of_Wealth": "Brian Portnoy",
        "The_Laws_of_Wealth": "Daniel Crosby",
        "Liar's_Poker": "Michael Lewis",
        "The_Big_Short": "Michael Lewis",
        "The_Investment_Answer": "Gordon Murray",
        "The_Behavior_Gap": "Carl Richards",
        "The_Little_Book_of_Behavioral_Investing": "James Montier",
        "The_Code_of_the_Extraordinary_Mind": "Vishen Lakhiani",
        "Everything_Is_F*cked": "Mark Manson",
        "What_Works_on_Wall_Street": "James O'Shaughnessy",
        "The_Index_Card": "Helaine Olen",
        "The_Algebra_of_Happiness": "Scott Galloway",
        "Money:_The_True_Story_of_a_Made-Up_Thing": "Jacob Goldstein",
        "The_Hour_Between_Dog_and_Wolf": "John Coates",
        "The_Behavioral_Investor": "Daniel Crosby",
        "Originals": "Adam Grant",
        "Show_Your_Work!": "Austin Kleon",
        "Crossing_the_Chasm": "Geoffrey A. Moore",
        "The_Subtle_Art_of_Not_Giving_a_F*ck": "Mark Manson",
        "The_Culture_Code": "Daniel Coyle",
        "The_Checklist_Manifesto": "Atul Gawande",
        "Steal_Like_an_Artist": "Austin Kleon",
        "Never_Split_the_Difference": "Chris Voss",
        "Skin_in_the_Game": "Nassim Nicholas Taleb",
        "The_Happiness_Hypothesis": "Jonathan Haidt",
        "Give_and_Take": "Adam Grant",
        "Think_Again": "Adam Grant",
        "The_Monk_Who_Sold_His_Ferrari": "Robin Sharma",
        "The_5_AM_Club": "Robin Sharma",
        "Common_Stocks_and_Uncommon_Profits": "Philip A. Fisher",
        "Value_Investing": "Bruce Greenwald",
        "The_Acquirer's_Multiple": "Tobias Carlisle",
        "The_Only_Investment_Guide_You'll_Ever_Need": "Andrew Tobias",
        "The_Bogleheads'_Guide_to_Retirement_Planning": "Taylor Larimore",
        "The_Intelligent_Asset_Allocator": "William J. Bernstein",
        "You_Can_Be_a_Stock_Market_Genius": "Joel Greenblatt",
        "Margin_of_Safety": "Seth Klarman",
        "The_Snowball": "Alice Schroeder",
        "The_Warren_Buffett_Way": "Robert Hagstrom",
        "Tribes": "Seth Godin",
        "Positioning": "Al Ries",
        "The_22_Immutable_Laws_of_Marketing": "Al Ries",
        "A_New_Earth": "Eckhart Tolle",
        "Purple_Cow": "Seth Godin",
        "The_Effective_Executive": "Peter Drucker",
        "The_Art_of_War": "Sun Tzu",
        "The_Law_of_Success": "Napoleon Hill",
        "The_First_90_Days": "Michael Watkins",
        "Crucial_Conversations": "Kerry Patterson",
        "The_4_Disciplines_of_Execution": "Chris McChesney",
        "Rich_Dad's_Guide_to_Investing": "Robert Kiyosaki",
        "Letters_from_a_Stoic": "Seneca",
        "Meditations": "Marcus Aurelius",
        "The_Art_of_Worldly_Wisdom": "Baltasar Gracian",
        "Pre-Suasion": "Robert Cialdini",
        "Contagious": "Jonah Berger",
        "Getting_Things_Done": "David Allen",
        "The_Power_of_Now": "Eckhart Tolle",
        "As_a_Man_Thinketh": "James Allen",
        "When": "Daniel H. Pink",
        "The_Art_of_Seduction": "Robert Greene",
        "David_and_Goliath": "Malcolm Gladwell",
        "Predictably_Irrational": "Dan Ariely",
        "Made_to_Stick": "Chip Heath",
        "Hooked": "Nir Eyal",
        "Measure_What_Matters": "John Doerr",
        "The_Innovator's_Dilemma": "Clayton M. Christensen",
        "So_Good_They_Can't_Ignore_You": "Cal Newport",
        "Range": "David Epstein",
        "Peak": "Anders Ericsson",
        "Influence": "Robert B. Cialdini",
        "The_Untethered_Soul": "Michael A. Singer",
        "Mindset": "Carol S. Dweck",
        "Common_Sense_on_Mutual_Funds": "John C. Bogle",
        "Stocks_for_the_Long_Run": "Jeremy J. Siegel",
        "The_Dhandho_Investor": "Mohnish Pabrai",
        "Security_Analysis": "Benjamin Graham",
        "The_Four_Pillars_of_Investing": "William J. Bernstein",
        "Nudge": "Richard H. Thaler",
        "How_to_Decide": "Annie Duke",
        "A_Mind_for_Numbers": "Barbara Oakley",
        "Digital_Minimalism": "Cal Newport",
        "The_One_Thing": "Gary Keller",
        "The_Mountain_Is_You": "Brianna Wiest",
        "The_Daily_Laws": "Robert Greene",
        "The_33_Strategies_of_War": "Robert Greene",
        "The_48_Laws_of_Power": "Robert Greene",
        "The_Dichotomy_of_Leadership": "Jocko Willink",
        "Leaders_Eat_Last": "Simon Sinek",
        "The_Infinite_Game": "Simon Sinek",
        "Start_with_Why": "Simon Sinek",
        "Drive": "Daniel Pink",
        "The_Tipping_Point": "Malcolm Gladwell",
        "Blink": "Malcolm Gladwell",
        "Outliers": "Malcolm Gladwell",
        "Grit": "Angela Duckworth",
        "Daring_Greatly": "Brené Brown",
        "The_Courage_to_Be_Disliked": "Ichiro Kishimi & Fumitake Koga",
        "The_4-Hour_Body": "Tim Ferriss",
        "Rich_Dad's_Increase_Your_Financial_IQ": "Robert Kiyosaki",
        "The_Bogleheads'_Guide_to_Investing": "Taylor Larimore",
        "Set_for_Life": "Scott Trench",
        "The_Book_on_Rental_Property_Investing": "Brandon Turner",
        "Linchpin": "Seth Godin",
        "The_Dip": "Seth Godin",
        "The_War_of_Art": "Steven Pressfield",
        "Stillness_Is_the_Key": "Ryan Holiday",
        "The_Daily_Stoic": "Ryan Holiday",
        "Models": "Mark Manson",
        "Extreme_Ownership": "Jocko Willink",
        "Discipline_Equals_Freedom": "Jocko Willink",
        "Can't_Hurt_Me": "David Goggins",
        "The_5_Second_Rule": "Mel Robbins",
        "High_Performance_Habits": "Brendon Burchard",
        "The_10X_Rule": "Grant Cardone",
        "Unlimited_Power": "Tony Robbins",
        "The_One_Minute_Millionaire": "Mark Victor Hansen",
        "Secrets_of_the_Millionaire_Mind": "T. Harv Eker",
        "The_Most_Important_Thing": "Howard Marks",
        "Poor_Charlie's_Almanack": "Charlie Munger",
        "The_Essays_of_Warren_Buffett": "Warren Buffett",
        "The_Wealthy_Barber": "David Chilton",
        "Tools_of_Titans": "Tim Ferriss",
        "How_to_Win_Friends_and_Influence_People": "Dale Carnegie",
        "Essentialism": "Greg McKeown",
        "Awaken_the_Giant_Within": "Tony Robbins",
        "Built_to_Last": "Jim Collins",
        "Shoe_Dog": "Phil Knight",
        "The_Hard_Thing_About_Hard_Things": "Ben Horowitz",
        "The_Personal_MBA": "Josh Kaufman",
        "Profit_First": "Mike Michalowicz",
        "The_Science_of_Getting_Rich": "Wallace D. Wattles",
        "You_Are_a_Badass_at_Making_Money": "Jen Sincero",
        "The_Miracle_Morning": "Hal Elrod",
        "The_Slight_Edge": "Jeff Olson",
        "Mastery": "Robert Greene",
        "The_Laws_of_Human_Nature": "Robert Greene",
        "Principles": "Ray Dalio",
        "Zero_to_One": "Peter Thiel",
        "The_$100_Startup": "Chris Guillebeau",
        "The_Power_of_Habit": "Charles Duhigg",
        "The_7_Habits_of_Highly_Effective_People": "Stephen R. Covey",
        "Deep_Work": "Cal Newport",
        "Ego_Is_the_Enemy": "Ryan Holiday",
        "The_Obstacle_Is_the_Way": "Ryan Holiday",
        "The_Almanack_of_Naval_Ravikant": "Eric Jorgenson",
        "The_Art_of_Thinking_Clearly": "Rolf Dobelli",
        "Thinking,_Fast_and_Slow": "Daniel Kahneman",
        "Antifragile": "Nassim Nicholas Taleb",
        "Fooled_by_Randomness": "Nassim Nicholas Taleb",
        "The_Black_Swan": "Nassim Nicholas Taleb",
        "The_Little_Book_That_Beats_the_Market": "Joel Greenblatt",
        "One_Up_On_Wall_Street": "Peter Lynch",
        "A_Random_Walk_Down_Wall_Street": "Burton G. Malkiel",
        "The_Barefoot_Investor": "Scott Pape",
        "Money:_Master_the_Game": "Tony Robbins",
        "The_Millionaire_Mind": "Thomas J. Stanley",
        "The_Automatic_Millionaire": "David Bach",
        "Psycho-Cybernetics": "Maxwell Maltz",
        "The_Bitcoin_Standard": "Saifedean Ammous",
        "Rich_Dad's_Cashflow_Quadrant": "Robert Kiyosaki",
        "The_Magic_of_Thinking_Big": "David J. Schwartz",
        "Unshakeable": "Tony Robbins",
        "The_Millionaire_Fastlane": "M.J. DeMarco",
        "I_Will_Teach_You_To_Be_Rich": "Ramit Sethi",
        "The_Compound_Effect": "Darren Hardy",
        "The_Richest_Man_in_Babylon": "George S. Clason",
        "Your_Money_or_Your_Life": "Vicki Robin",
        "The_Little_Book_of_Common_Sense_Investing": "John C. Bogle",
        "The_Intelligent_Investor": "Benjamin Graham",
        "The_Lean_Startup": "Eric Ries",
        "Good_to_Great": "Jim Collins",
        "The_80-20_Principle": "Richard Koch",
        "The_Comfort_Crisis": "Michael Easter",
        "Feel_the_Fear_and_Do_It_Anyway": "Susan Jeffers",
        "The_Happiness_Project": "Gretchen Rubin",
        "The_4-Hour_Chef": "Timothy Ferriss",
        "Permission_Marketing": "Seth Godin",
        "The_Halo_Effect": "Phil Rosenzweig",
        "Creativity,_Inc.": "Ed Catmull",
        "The_Alliance": "Reid Hoffman",
        "To_Sell_Is_Human": "Daniel Pink",
        "A_Whole_New_Mind": "Daniel Pink",
        "The_Artist's_Way": "Julia Cameron",
        "Big_Magic": "Elizabeth Gilbert",
        "Dare_to_Lead": "Brené Brown",
        "Talking_to_Strangers": "Malcolm Gladwell",
        "Side_Hustle": "Chris Guillebeau",
        "The_Education_of_a_Value_Investor": "Guy Spier",
        "The_Second_Machine_Age": "Erik Brynjolfsson",
        "Good_Profit": "Charles Koch",
        "The_Everything_Store": "Brad Stone",
        "The_Wealth_Money_Can't_Buy": "Robin Sharma",
        "Buy_Back_Your_Time": "Dan Martell",
        "The_Diary_of_a_CEO": "Steven Bartlett",
        "10x_Is_Easier_Than_2x": "Dan Sullivan",
        "The_Coming_Wave": "Mustafa Suleyman",
        "Right_Kind_of_Wrong": "Amy Edmondson",
        "Hidden_Potential": "Adam Grant",
        "The_Perfection_Trap": "Thomas Curran",
        "Supercommunicators": "Charles Duhigg",
        "The_Anxious_Generation": "Jonathan Haidt",
        "Outlive": "Peter Attia",
        "Build_the_Life_You_Want": "Arthur Brooks",
        "Master_of_Change": "Brad Stulberg",
        "The_Ride_of_a_Lifetime": "Robert Iger",
        "The_Bezos_Blueprint": "Carmine Gallo",
        "Unreasonable_Hospitality": "Will Guidara",
        "The_Practice_of_Groundedness": "Brad Stulberg",
        "Think_Remarkable": "Guy Kawasaki",
        "The_Friction_Project": "Robert Sutton",
        "Making_Numbers_Count": "Chip Heath",
        # --- batch-added 2026-08-12 ---
        "The_Art_of_Learning": "Josh Waitzkin",
        "Stolen_Focus": "Johann Hari",
        "Thinking_in_Bets": "Annie Duke",
        "Switch": "Chip Heath & Dan Heath",
        "Decisive": "Chip Heath & Dan Heath",
        "The_Power_of_Moments": "Chip Heath & Dan Heath",
        "The_Talent_Code": "Daniel Coyle",
        "The_Coddling_of_the_American_Mind": "Greg Lukianoff & Jonathan Haidt",
        "The_Scout_Mindset": "Julia Galef",
        "Superforecasting": "Philip E. Tetlock",
        "The_Signal_and_the_Noise": "Nate Silver",
        "Clear_Thinking": "Shane Parrish",
        "The_Great_Mental_Models": "Shane Parrish",
        "The_Motivation_Myth": "Jeff Haden",
        "Ultralearning": "Scott H. Young",
        "The_Happiness_Trap": "Russ Harris",
        "The_Courage_to_Be_Happy": "Ichiro Kishimi & Fumitake Koga",
        "The_Art_of_the_Good_Life": "Rolf Dobelli",
        "The_5_Elements_of_Effective_Thinking": "Edward B. Burger & Michael Starbird",
        "The_Advice_Trap": "Michael Bungay Stanier",
        # --- batch-added 2026-08-17 ---
        "A_Guide_to_the_Good_Life": "William B. Irvine",
        "The_Four_Steps_to_the_Epiphany": "Steve Blank",
        "Business_Model_Generation": "Alexander Osterwalder",
        "Value_Proposition_Design": "Alexander Osterwalder",
        "How_to_Make_Money_in_Stocks": "William J. O'Neil",
        "Enough": "John C. Bogle",
        "The_Bed_of_Procrustes": "Nassim Nicholas Taleb",
        "Tax-Free_Wealth": "Tom Wheelwright",
        "The_Paradox_of_Choice": "Barry Schwartz",
        "The_Four_Tendencies": "Gretchen Rubin",
        "The_Body_Keeps_the_Score": "Bessel van der Kolk",
        "Attached": "Amir Levine",
        "Nonviolent_Communication": "Marshall Rosenberg",
        "The_Undoing_Project": "Michael Lewis",
        "The_Blind_Side": "Michael Lewis",
        "Boomerang": "Michael Lewis",
        "The_New_New_Thing": "Michael Lewis",
        "The_Smartest_Guys_in_the_Room": "Bethany McLean",
        "Too_Big_to_Fail": "Andrew Ross Sorkin",
        "The_Phoenix_Project": "Gene Kim",
        "Smarter_Faster_Better": "Charles Duhigg",
        "The_Honest_Truth_About_Dishonesty": "Dan Ariely",
        "Misbehaving": "Richard Thaler",
        "The_Little_Book_That_Still_Beats_the_Market": "Joel Greenblatt",
        "One_Up_on_Wall_Street": "Peter Lynch",
        "The_Little_Book_That_Builds_Wealth": "Pat Dorsey",
        "The_Wealthy_Barber_Returns": "David Chilton",
        "Personal_Finance_for_Dummies": "Eric Tyson",
        "The_9_Steps_to_Financial_Freedom": "Suze Orman",
        "The_Power_of_Vulnerability": "Brené Brown",
        "The_ABCs_of_Real_Estate_Investing": "Ken McElroy",
        "Great_by_Choice": "Jim Collins",
        "The_Practice_of_Management": "Peter Drucker",
        "The_Four": "Scott Galloway",
        "Noise": "Daniel Kahneman",
        "The_E-Myth_Manager": "Michael Gerber",
        "Smart_Women_Finish_Rich": "David Bach",
        "It_Doesn't_Have_to_Be_Crazy_at_Work": "Jason Fried",
        # --- batch-added 2026-08-22 ---
        "The_Prince": "Niccolò Machiavelli",
        "The_Art_of_Happiness": "Dalai Lama & Howard Cutler",
        "Creative_Confidence": "Tom Kelley & David Kelley",
        "The_Bomber_Mafia": "Malcolm Gladwell",
        "What_the_Dog_Saw": "Malcolm Gladwell",
        "Get_Good_with_Money": "Tiffany Aliche",
        "How_the_Mighty_Fall": "Jim Collins",
        "How_Will_You_Measure_Your_Life": "Clayton M. Christensen",
        "Atlas_of_the_Heart": "Brené Brown",
        "Option_B": "Sheryl Sandberg & Adam Grant",
        "Discipline_Is_Destiny": "Ryan Holiday",
        "The_Fifth_Risk": "Michael Lewis",
        "Going_Infinite": "Michael Lewis",
        "The_Greatness_Guide": "Robin Sharma",
        "Dollars_and_Sense": "Dan Ariely",
        "StrengthsFinder_2.0": "Tom Rath",
        "First_Break_All_the_Rules": "Marcus Buckingham & Curt Coffman",
        "Turning_Pro": "Steven Pressfield",
        "Choose_Yourself": "James Altucher",
        "The_Art_of_Non-Conformity": "Chris Guillebeau",
    }
    return m.get(title, "")


def _data_js():
    lines = []
    for fn in _books():
        t = fn.replace("_", " ")
        a = _author_for(fn)
        lines.append(f'  {{t:"{t}", a:"{a}", f:"{fn}"}},')
    return "\n".join(lines)


def main():
    if len(sys.argv) >= 3:
        title, author = sys.argv[1], sys.argv[2]
        # 1. generate PDF if missing
        fn = title.replace(" ", "_")
        pdf = BASE / "pdf" / f"{fn}.pdf"
        if not pdf.exists():
            subprocess.run(f"bash -c 'source {VENV} && python3 scripts/gen_pdf.py \"{title}\" \"{author}\"'",
                           shell=True, cwd=str(BASE))
            if not pdf.exists():
                print("PDF gen failed"); sys.exit(1)
        # remember author for future scans
        _remembrance(title, author)
    # 2. rebuild data arrays in both pages
    data = _data_js()
    for page in ("index.html", "books.html"):
        p = BASE / page
        html = p.read_text()
        import re
        html = re.sub(r"<!-- BOOKS_DATA -->.*?<!-- /BOOKS_DATA -->",
                       f"<!-- BOOKS_DATA -->\n{data}\n  <!-- /BOOKS_DATA -->", html, flags=re.DOTALL)
        p.write_text(html)
    print(f"[site] rebuilt book data: {len(_books())} books in {', '.join(_books()[:3])}...")


def _remembrance(title, author):
    """Store author mapping persistently (used by _author_for)."""
    m = {
        "Atomic_Habits": "James Clear",
        "The_Psychology_of_Money": "Morgan Housel",
        "Rich_Dad_Poor_Dad": "Robert Kiyosaki",
        "The_4-Hour_Workweek": "Timothy Ferriss",
        "The_Simple_Path_to_Wealth": "JL Collins",
        "The_Psychology_of_Human_Misjudgment": "Charlie Munger",
        "The_E-Myth_Revisited": "Michael Gerber",
        "The_Total_Money_Makeover": "Dave Ramsey",
        "Think_and_Grow_Rich": "Napoleon Hill",
        "The_Millionaire_Next_Door": "Thomas J. Stanley",
        "The_Wisdom_of_Finance": "Mihir Desai",
        "Devil_Take_the_Hindmost": "Edward Chancellor",
        "The_Only_Three_Questions_That_Count": "Ken Fisher",
        "Money_Mischief": "Milton Friedman",
        "The_House_of_Morgan": "Ron Chernow",
        "Tap_Dancing_to_Work": "Carol Loomis",
        "The_Ten_Roads_to_Riches": "Ken Fisher",
        "The_Interpretation_of_Financial_Statements": "Benjamin Graham",
        "The_Investment_Checklist": "Michael Shearn",
        "Financial_Shenanigans": "Howard Schilit",
        "More_Money_Than_God": "Sebastian Mallaby",
        "The_Great_Crash_1929": "John Kenneth Galbraith",
        "The_Ascent_of_Money": "Niall Ferguson",
        "Den_of_Thieves": "James B. Stewart",
        "Barbarians_at_the_Gate": "Bryan Burrough",
        "When_Genius_Failed": "Roger Lowenstein",
        "The_Clash_of_the_Cultures": "John C. Bogle",
        "The_Money_Game": "George Goodman",
        "Where_Are_the_Customers'_Yachts?": "Fred Schwed",
        "The_Zurich_Axioms": "Max Gunther",
        "The_Phoenix_Project": "Gene Kim",
        "Too_Big_to_Fail": "Andrew Ross Sorkin",
        "The_Smartest_Guys_in_the_Room": "Bethany McLean",
        "The_New_New_Thing": "Michael Lewis",
        "Boomerang": "Michael Lewis",
        "The_Blind_Side": "Michael Lewis",
        "The_Undoing_Project": "Michael Lewis",
        "Nonviolent_Communication": "Marshall Rosenberg",
        "Attached": "Amir Levine",
        "The_Body_Keeps_the_Score": "Bessel van der Kolk",
        "The_Four_Tendencies": "Gretchen Rubin",
        "The_Paradox_of_Choice": "Barry Schwartz",
        "Tax-Free_Wealth": "Tom Wheelwright",
        "The_Bed_of_Procrustes": "Nassim Nicholas Taleb",
        "Enough": "John C. Bogle",
        "How_to_Make_Money_in_Stocks": "William J. O'Neil",
        "Value_Proposition_Design": "Alexander Osterwalder",
        "Business_Model_Generation": "Alexander Osterwalder",
        "The_Four_Steps_to_the_Epiphany": "Steve Blank",
        "A_Guide_to_the_Good_Life": "William B. Irvine",
        "Happier": "Tal Ben-Shahar",
        "Meatball_Sundae": "Seth Godin",
        "The_E-Myth_Mastery": "Michael Gerber",
        "The_Icarus_Deception": "Seth Godin",
        "The_Charisma_Myth": "Olivia Fox Cabane",
        "The_Miracle_of_Mindfulness": "Thich Nhat Hanh",
        "10%_Happier": "Dan Harris",
        "The_Happiness_Equation": "Neil Pasricha",
        "Designing_Your_Life": "Bill Burnett & Dave Evans",
        "Do_the_Work": "Steven Pressfield",
        "The_Practice": "Seth Godin",
        "The_First_20_Hours": "Josh Kaufman",
        "The_Investor's_Paradox": "Michael Pompian",
        "Millionaire_Teacher": "Andrew Hallam",
        "The_Misbehavior_of_Markets": "Benoit Mandelbrot",
        "Irrational_Exuberance": "Robert Shiller",
        "Fortune's_Formula": "William Poundstone",
        "Against_the_Gods": "Peter L. Bernstein",
        "The_Drunkard's_Walk": "Leonard Mlodinow",
        "The_Outsiders": "William Thorndike",
        "A_Million_Bucks_by_30": "Alan Corey",
        "The_Hedge_Fund_Mirage": "Simon Lack",
        "The_Bond_Book": "Annette Thau",
        "The_Single_Best_Investment": "Lowell Miller",
        "The_Investors_Manifesto": "William Bernstein",
        "Winning_the_Losers_Game": "Charles Ellis",
        "Unconventional_Success": "David Swensen",
        "Flash_Boys": "Michael Lewis",
        "Moneyball": "Michael Lewis",
        "Thinking_Fast_and_Slow": "Daniel Kahneman",
        "Quiet": "Susan Cain",
        "The_Startup_Owners_Manual": "Steve Blank",
        "The_Innovators_Dilemma": "Clayton Christensen",
        "The_Dao_of_Capital": "Mark Spitznagel",
        "The_Wealthy_Gardener": "John Soforic",
        "You_Are_a_Badass": "Jen Sincero",
        "Poor_Charlies_Almanack": "Charlie Munger",
        "The_Gap_and_The_Gain": "Dan Sullivan",
        "The_Cashflow_Quadrant": "Robert Kiyosaki",
        "The_Bogleheads_Guide_to_Investing": "Taylor Larimore",
        "Keep_Going": "Austin Kleon",
        "Rising_Strong": "Brene Brown",
        "The_Confidence_Code": "Katty Kay",
        "The_Long_Game": "Dorie Clark",
        "Slow_Productivity": "Cal Newport",
        "A_World_Without_Email": "Cal Newport",
        "Talent": "Tyler Cowen",
        "The_Sports_Gene": "David Epstein",
        "The_Mastery_of_Love": "Don Miguel Ruiz",
        "The_Fifth_Agreement": "Don Miguel Ruiz",
        "Work_Rules": "Laszlo Bock",
        "Thanks_for_the_Feedback": "Douglas Stone",
        "Difficult_Conversations": "Douglas Stone",
        "The_Power_of_Regret": "Daniel H. Pink",
        "No_Rules_Rules": "Reed Hastings",
        "Relentless": "Tim S. Grover",
        "Make_It_Stick": "Peter C. Brown",
        "The_5_Types_of_Wealth": "Sahil Bloom",
        "The_Algebra_of_Wealth": "Scott Galloway",
        "Same_as_Ever": "Morgan Housel",
        "The_Tao_of_Warren_Buffett": "Mary Buffett",
        "The_New_Buffettology": "Mary Buffett",
        "Buffettology": "Mary Buffett",
        "The_Warren_Buffett_Portfolio": "Robert G. Hagstrom",
        "Reminiscences_of_a_Stock_Operator": "Edwin Lefevre",
        "Trading_in_the_Zone": "Mark Douglas",
        "The_Complete_Turtle_Trader": "Michael Covel",
        "Trend_Following": "Michael Covel",
        "Market_Wizards": "Jack D. Schwager",
        "The_Five_Rules_for_Successful_Stock_Investing": "Pat Dorsey",
        "The_Little_Book_of_Valuation": "Aswath Damodaran",
        "Seeking_Wisdom": "Peter Bevelin",
        "The_Bogleheads'_Guide_to_the_Three-Fund_Portfolio": "Taylor Larimore",
        "Your_Money_and_Your_Brain": "Jason Zweig",
        "The_Second_Mountain": "David Brooks",
        "The_Road_to_Character": "David Brooks",
        "The_Social_Animal": "David Brooks",
        "The_Righteous_Mind": "Jonathan Haidt",
        "The_Next_Millionaire_Next_Door": "Sarah Stanley Fallaw",
        "The_Millionaire_Women_Next_Door": "Thomas J. Stanley",
        "Flow": "Mihaly Csikszentmihalyi",
        "The_Power_of_Positive_Thinking": "Norman Vincent Peale",
        "Remote": "Jason Fried",
        "Team_of_Teams": "Stanley McChrystal",
        "The_Coaching_Habit": "Michael Bungay Stanier",
        "The_Innovator's_Solution": "Clayton M. Christensen",
        "The_Shallows": "Nicholas Carr",
        "Stumbling_on_Happiness": "Daniel Gilbert",
        "The_Gifts_of_Imperfection": "Brené Brown",
        "Braving_the_Wilderness": "Brené Brown",
        "The_Creative_Act": "Rick Rubin",
        "The_50th_Law": "Robert Greene",
        "The_Smart_Money_Woman": "Arese Ugwu",
        "The_One-Page_Financial_Plan": "Carl Richards",
        "Rich_Dad's_Who_Took_My_Money?": "Robert Kiyosaki",
        "The_Power_of_Intention": "Wayne W. Dyer",
        "The_8th_Habit": "Stephen R. Covey",
        "The_Alchemist": "Paulo Coelho",
        "The_5_Love_Languages": "Gary Chapman",
        "First_Things_First": "Stephen R. Covey",
        "Man's_Search_for_Meaning": "Viktor E. Frankl",
        "The_Four_Agreements": "Don Miguel Ruiz",
        "Who_Will_Cry_When_You_Die?": "Robin Sharma",
        "Courage_Is_Calling": "Ryan Holiday",
        "Lives_of_the_Stoics": "Ryan Holiday",
        "Outwitting_the_Devil": "Napoleon Hill",
        "Success_Through_a_Positive_Mental_Attitude": "Napoleon Hill",
        "The_Go-Giver": "Bob Burg",
        "The_Success_Principles": "Jack Canfield",
        "Financial_Peace_Revisited": "Dave Ramsey",
        "Learn_to_Earn": "Peter Lynch",
        "Beating_the_Street": "Peter Lynch",
        "Buffett:_The_Making_of_an_American_Capitalist": "Roger Lowenstein",
        "Stop_Acting_Rich": "Thomas J. Stanley",
        "Tribe_of_Mentors": "Timothy Ferriss",
        "How_to_Stop_Worrying_and_Start_Living": "Dale Carnegie",
        "The_Money_Book_for_the_Young,_Fabulous_&_Broke": "Suze Orman",
        "Concentrated_Investing": "Allen Benello",
        "Deep_Value": "Tobias Carlisle",
        "The_Investor's_Manifesto": "William J. Bernstein",
        "The_Little_Book_of_Value_Investing": "Christopher Browne",
        "Marketing_Made_Simple": "Donald Miller",
        "Hyperfocus": "Chris Bailey",
        "The_Outward_Mindset": "The Arbinger Institute",
        "The_Power_of_Less": "Leo Babauta",
        "All_Marketers_Are_Liars": "Seth Godin",
        "Running_Lean": "Ash Maurya",
        "The_Willpower_Instinct": "Kelly McGonigal",
        "They_Ask_You_Answer": "Marcus Sheridan",
        "The_Advantage": "Patrick Lencioni",
        "The_Startup_Owner's_Manual": "Steve Blank",
        "Indistractable": "Nir Eyal",
        "Tiny_Habits": "B.J. Fogg",
        "The_1-Page_Marketing_Plan": "Allan Dib",
        "The_Toyota_Way": "Jeffrey Liker",
        "Turn_the_Ship_Around!": "L. David Marquet",
        "This_Is_Marketing": "Seth Godin",
        "The_Lean_Product_Playbook": "Dan Olsen",
        "The_Founder's_Dilemmas": "Noam Wasserman",
        "High_Growth_Handbook": "Elad Gil",
        "Winning": "Jack Welch",
        "The_Score_Takes_Care_of_Itself": "Bill Walsh",
        "The_Culture_Map": "Erin Meyer",
        "Radical_Candor": "Kim Scott",
        "Multipliers": "Liz Wiseman",
        "The_Power_of_Full_Engagement": "Jim Loehr",
        "The_Happiness_Advantage": "Shawn Achor",
        "The_Art_of_Possibility": "Rosamund Stone Zander",
        "Venture_Deals": "Brad Feld",
        "Founders_at_Work": "Jessica Livingston",
        "The_21_Irrefutable_Laws_of_Leadership": "John C. Maxwell",
        "Leadership_and_Self-Deception": "The Arbinger Institute",
        "The_Five_Dysfunctions_of_a_Team": "Patrick Lencioni",
        "Predictable_Revenue": "Aaron Ross",
        "The_Challenger_Sale": "Matthew Dixon",
        "The_Art_of_the_Start": "Guy Kawasaki",
        "The_One_Minute_Manager": "Ken Blanchard",
        "Blitzscaling": "Reid Hoffman",
        "The_Sales_Bible": "Jeffrey Gitomer",
        "Jab,_Jab,_Jab,_Right_Hook": "Gary Vaynerchuk",
        "Crushing_It!": "Gary Vaynerchuk",
        "The_Cold_Start_Problem": "Andrew Chen",
        "Obviously_Awesome": "April Dunford",
        "Playing_to_Win": "A.G. Lafley",
        "Competing_Against_Luck": "Clayton M. Christensen",
        "The_Goal": "Eliyahu M. Goldratt",
        "Only_the_Paranoid_Survive": "Andrew S. Grove",
        "High_Output_Management": "Andrew S. Grove",
        "The_Great_CEO_Within": "Matt Mochary",
        "Key_Person_of_Influence": "Daniel Priestley",
        "Oversubscribed": "Daniel Priestley",
        "Traffic_Secrets": "Russell Brunson",
        "Dotcom_Secrets": "Russell Brunson",
        "Expert_Secrets": "Russell Brunson",
        "The_Ultimate_Sales_Machine": "Chet Holmes",
        "Building_a_StoryBrand": "Donald Miller",
        "Little_Red_Book_of_Selling": "Jeffrey Gitomer",
        "The_Lean_Six_Sigma_Pocket_Toolbook": "Michael L. George",
        "The_Sales_Acceleration_Formula": "Mark Roberge",
        "Amp_It_Up": "Frank Slootman",
        "Trillion_Dollar_Coach": "Eric Schmidt",
        "Broke_Millennial": "Erin Lowry",
        "The_White_Coat_Investor": "James M. Dahle",
        "Just_Keep_Buying": "Nick Maggiulli",
        "Die_With_Zero": "Bill Perkins",
        "Quit_Like_a_Millionaire": "Kristy Shen",
        "Financial_Freedom": "Grant Sabatier",
        "The_Millionaire_Real_Estate_Investor": "Gary Keller",
        "Getting_to_Yes": "Roger Fisher",
        "Eat_That_Frog": "Brian Tracy",
        "The_12_Week_Year": "Brian Moran",
        "Company_of_One": "Paul Jarvis",
        "Rework": "Jason Fried",
        "The_Mom_Test": "Rob Fitzpatrick",
        "Good_Strategy_Bad_Strategy": "Richard Rumelt",
        "Blue_Ocean_Strategy": "W. Chan Kim",
        "Scaling_Up": "Verne Harnish",
        "Traction": "Gino Wickman",
        "The_Geometry_of_Wealth": "Brian Portnoy",
        "The_Laws_of_Wealth": "Daniel Crosby",
        "Liar's_Poker": "Michael Lewis",
        "The_Big_Short": "Michael Lewis",
        "The_Investment_Answer": "Gordon Murray",
        "The_Behavior_Gap": "Carl Richards",
        "The_Little_Book_of_Behavioral_Investing": "James Montier",
        "The_Code_of_the_Extraordinary_Mind": "Vishen Lakhiani",
        "Everything_Is_F*cked": "Mark Manson",
        "What_Works_on_Wall_Street": "James O'Shaughnessy",
        "The_Index_Card": "Helaine Olen",
        "The_Algebra_of_Happiness": "Scott Galloway",
        "Money:_The_True_Story_of_a_Made-Up_Thing": "Jacob Goldstein",
        "The_Hour_Between_Dog_and_Wolf": "John Coates",
        "The_Behavioral_Investor": "Daniel Crosby",
        "Originals": "Adam Grant",
        "Show_Your_Work!": "Austin Kleon",
        "Crossing_the_Chasm": "Geoffrey A. Moore",
        "The_Subtle_Art_of_Not_Giving_a_F*ck": "Mark Manson",
        "The_Culture_Code": "Daniel Coyle",
        "The_Checklist_Manifesto": "Atul Gawande",
        "Steal_Like_an_Artist": "Austin Kleon",
        "Never_Split_the_Difference": "Chris Voss",
        "Skin_in_the_Game": "Nassim Nicholas Taleb",
        "The_Happiness_Hypothesis": "Jonathan Haidt",
        "Give_and_Take": "Adam Grant",
        "Think_Again": "Adam Grant",
        "The_Monk_Who_Sold_His_Ferrari": "Robin Sharma",
        "The_5_AM_Club": "Robin Sharma",
        "Common_Stocks_and_Uncommon_Profits": "Philip A. Fisher",
        "Value_Investing": "Bruce Greenwald",
        "The_Acquirer's_Multiple": "Tobias Carlisle",
        "The_Only_Investment_Guide_You'll_Ever_Need": "Andrew Tobias",
        "The_Bogleheads'_Guide_to_Retirement_Planning": "Taylor Larimore",
        "The_Intelligent_Asset_Allocator": "William J. Bernstein",
        "You_Can_Be_a_Stock_Market_Genius": "Joel Greenblatt",
        "Margin_of_Safety": "Seth Klarman",
        "The_Snowball": "Alice Schroeder",
        "The_Warren_Buffett_Way": "Robert Hagstrom",
        "Tribes": "Seth Godin",
        "Positioning": "Al Ries",
        "The_22_Immutable_Laws_of_Marketing": "Al Ries",
        "A_New_Earth": "Eckhart Tolle",
        "Purple_Cow": "Seth Godin",
        "The_Effective_Executive": "Peter Drucker",
        "The_Art_of_War": "Sun Tzu",
        "The_Law_of_Success": "Napoleon Hill",
        "The_First_90_Days": "Michael Watkins",
        "Crucial_Conversations": "Kerry Patterson",
        "The_4_Disciplines_of_Execution": "Chris McChesney",
        "Rich_Dad's_Guide_to_Investing": "Robert Kiyosaki",
        "Letters_from_a_Stoic": "Seneca",
        "Meditations": "Marcus Aurelius",
        "The_Art_of_Worldly_Wisdom": "Baltasar Gracian",
        "Pre-Suasion": "Robert Cialdini",
        "Contagious": "Jonah Berger",
        "Getting_Things_Done": "David Allen",
        "The_Power_of_Now": "Eckhart Tolle",
        "As_a_Man_Thinketh": "James Allen",
        "When": "Daniel H. Pink",
        "The_Art_of_Seduction": "Robert Greene",
        "David_and_Goliath": "Malcolm Gladwell",
        "Predictably_Irrational": "Dan Ariely",
        "Made_to_Stick": "Chip Heath",
        "Hooked": "Nir Eyal",
        "Measure_What_Matters": "John Doerr",
        "The_Innovator's_Dilemma": "Clayton M. Christensen",
        "So_Good_They_Can't_Ignore_You": "Cal Newport",
        "Range": "David Epstein",
        "Peak": "Anders Ericsson",
        "Influence": "Robert B. Cialdini",
        "The_Untethered_Soul": "Michael A. Singer",
        "Mindset": "Carol S. Dweck",
        "Common_Sense_on_Mutual_Funds": "John C. Bogle",
        "Stocks_for_the_Long_Run": "Jeremy J. Siegel",
        "The_Dhandho_Investor": "Mohnish Pabrai",
        "Security_Analysis": "Benjamin Graham",
        "The_Four_Pillars_of_Investing": "William J. Bernstein",
        "Nudge": "Richard H. Thaler",
        "How_to_Decide": "Annie Duke",
        "A_Mind_for_Numbers": "Barbara Oakley",
        "Digital_Minimalism": "Cal Newport",
        "The_One_Thing": "Gary Keller",
        "The_Mountain_Is_You": "Brianna Wiest",
        "The_Daily_Laws": "Robert Greene",
        "The_33_Strategies_of_War": "Robert Greene",
        "The_48_Laws_of_Power": "Robert Greene",
        "The_Dichotomy_of_Leadership": "Jocko Willink",
        "Leaders_Eat_Last": "Simon Sinek",
        "The_Infinite_Game": "Simon Sinek",
        "Start_with_Why": "Simon Sinek",
        "Drive": "Daniel Pink",
        "The_Tipping_Point": "Malcolm Gladwell",
        "Blink": "Malcolm Gladwell",
        "Outliers": "Malcolm Gladwell",
        "Grit": "Angela Duckworth",
        "Daring_Greatly": "Brené Brown",
        "The_Courage_to_Be_Disliked": "Ichiro Kishimi & Fumitake Koga",
        "The_4-Hour_Body": "Tim Ferriss",
        "Rich_Dad's_Increase_Your_Financial_IQ": "Robert Kiyosaki",
        "The_Bogleheads'_Guide_to_Investing": "Taylor Larimore",
        "Set_for_Life": "Scott Trench",
        "The_Book_on_Rental_Property_Investing": "Brandon Turner",
        "Linchpin": "Seth Godin",
        "The_Dip": "Seth Godin",
        "The_War_of_Art": "Steven Pressfield",
        "Stillness_Is_the_Key": "Ryan Holiday",
        "The_Daily_Stoic": "Ryan Holiday",
        "Models": "Mark Manson",
        "Extreme_Ownership": "Jocko Willink",
        "Discipline_Equals_Freedom": "Jocko Willink",
        "Can't_Hurt_Me": "David Goggins",
        "The_5_Second_Rule": "Mel Robbins",
        "High_Performance_Habits": "Brendon Burchard",
        "The_10X_Rule": "Grant Cardone",
        "Unlimited_Power": "Tony Robbins",
        "The_One_Minute_Millionaire": "Mark Victor Hansen",
        "Secrets_of_the_Millionaire_Mind": "T. Harv Eker",
        "The_Most_Important_Thing": "Howard Marks",
        "Poor_Charlie's_Almanack": "Charlie Munger",
        "The_Essays_of_Warren_Buffett": "Warren Buffett",
        "The_Wealthy_Barber": "David Chilton",
        "Tools_of_Titans": "Tim Ferriss",
        "How_to_Win_Friends_and_Influence_People": "Dale Carnegie",
        "Essentialism": "Greg McKeown",
        "Awaken_the_Giant_Within": "Tony Robbins",
        "Built_to_Last": "Jim Collins",
        "Shoe_Dog": "Phil Knight",
        "The_Hard_Thing_About_Hard_Things": "Ben Horowitz",
        "The_Personal_MBA": "Josh Kaufman",
        "Profit_First": "Mike Michalowicz",
        "The_Science_of_Getting_Rich": "Wallace D. Wattles",
        "You_Are_a_Badass_at_Making_Money": "Jen Sincero",
        "The_Miracle_Morning": "Hal Elrod",
        "The_Slight_Edge": "Jeff Olson",
        "Mastery": "Robert Greene",
        "The_Laws_of_Human_Nature": "Robert Greene",
        "Principles": "Ray Dalio",
        "Zero_to_One": "Peter Thiel",
        "The_$100_Startup": "Chris Guillebeau",
        "The_Power_of_Habit": "Charles Duhigg",
        "The_7_Habits_of_Highly_Effective_People": "Stephen R. Covey",
        "Deep_Work": "Cal Newport",
        "Ego_Is_the_Enemy": "Ryan Holiday",
        "The_Obstacle_Is_the_Way": "Ryan Holiday",
        "The_Almanack_of_Naval_Ravikant": "Eric Jorgenson",
        "The_Art_of_Thinking_Clearly": "Rolf Dobelli",
        "Thinking,_Fast_and_Slow": "Daniel Kahneman",
        "Antifragile": "Nassim Nicholas Taleb",
        "Fooled_by_Randomness": "Nassim Nicholas Taleb",
        "The_Black_Swan": "Nassim Nicholas Taleb",
        "The_Little_Book_That_Beats_the_Market": "Joel Greenblatt",
        "One_Up_On_Wall_Street": "Peter Lynch",
        "A_Random_Walk_Down_Wall_Street": "Burton G. Malkiel",
        "The_Barefoot_Investor": "Scott Pape",
        "Money:_Master_the_Game": "Tony Robbins",
        "The_Millionaire_Mind": "Thomas J. Stanley",
        "The_Automatic_Millionaire": "David Bach",
        "Psycho-Cybernetics": "Maxwell Maltz",
        "The_Bitcoin_Standard": "Saifedean Ammous",
        "Rich_Dad's_Cashflow_Quadrant": "Robert Kiyosaki",
        "The_Magic_of_Thinking_Big": "David J. Schwartz",
        "Unshakeable": "Tony Robbins",
        "The_Millionaire_Fastlane": "M.J. DeMarco",
        "I_Will_Teach_You_To_Be_Rich": "Ramit Sethi",
        "The_Compound_Effect": "Darren Hardy",
        "The_Richest_Man_in_Babylon": "George S. Clason",
        "Your_Money_or_Your_Life": "Vicki Robin",
        "The_Little_Book_of_Common_Sense_Investing": "John C. Bogle",
        "The_Intelligent_Investor": "Benjamin Graham",
        "The_Lean_Startup": "Eric Ries",
        "Good_to_Great": "Jim Collins",
        "The_80-20_Principle": "Richard Koch",
        "The_Comfort_Crisis": "Michael Easter",
        "Feel_the_Fear_and_Do_It_Anyway": "Susan Jeffers",
        "The_Happiness_Project": "Gretchen Rubin",
        "The_4-Hour_Chef": "Timothy Ferriss",
        "Permission_Marketing": "Seth Godin",
        "The_Halo_Effect": "Phil Rosenzweig",
        "Creativity,_Inc.": "Ed Catmull",
        "The_Alliance": "Reid Hoffman",
        "To_Sell_Is_Human": "Daniel Pink",
        "A_Whole_New_Mind": "Daniel Pink",
        "The_Artist's_Way": "Julia Cameron",
        "Big_Magic": "Elizabeth Gilbert",
        "Dare_to_Lead": "Brené Brown",
        "Talking_to_Strangers": "Malcolm Gladwell",
        "Side_Hustle": "Chris Guillebeau",
        "The_Education_of_a_Value_Investor": "Guy Spier",
        "The_Second_Machine_Age": "Erik Brynjolfsson",
        "Good_Profit": "Charles Koch",
        "The_Everything_Store": "Brad Stone",
        "The_Wealth_Money_Can't_Buy": "Robin Sharma",
        "Buy_Back_Your_Time": "Dan Martell",
        "The_Diary_of_a_CEO": "Steven Bartlett",
        "10x_Is_Easier_Than_2x": "Dan Sullivan",
        "The_Coming_Wave": "Mustafa Suleyman",
        "Right_Kind_of_Wrong": "Amy Edmondson",
        "Hidden_Potential": "Adam Grant",
        "The_Perfection_Trap": "Thomas Curran",
        "Supercommunicators": "Charles Duhigg",
        "The_Anxious_Generation": "Jonathan Haidt",
        "Outlive": "Peter Attia",
        "Build_the_Life_You_Want": "Arthur Brooks",
        "Master_of_Change": "Brad Stulberg",
        "The_Ride_of_a_Lifetime": "Robert Iger",
        "The_Bezos_Blueprint": "Carmine Gallo",
        "Unreasonable_Hospitality": "Will Guidara",
        "The_Practice_of_Groundedness": "Brad Stulberg",
        "Think_Remarkable": "Guy Kawasaki",
        "The_Friction_Project": "Robert Sutton",
        "Making_Numbers_Count": "Chip Heath",
        # --- batch-added 2026-08-12 ---
        "The_Art_of_Learning": "Josh Waitzkin",
        "Stolen_Focus": "Johann Hari",
        "Thinking_in_Bets": "Annie Duke",
        "Switch": "Chip Heath & Dan Heath",
        "Decisive": "Chip Heath & Dan Heath",
        "The_Power_of_Moments": "Chip Heath & Dan Heath",
        "The_Talent_Code": "Daniel Coyle",
        "The_Coddling_of_the_American_Mind": "Greg Lukianoff & Jonathan Haidt",
        "The_Scout_Mindset": "Julia Galef",
        "Superforecasting": "Philip E. Tetlock",
        "The_Signal_and_the_Noise": "Nate Silver",
        "Clear_Thinking": "Shane Parrish",
        "The_Great_Mental_Models": "Shane Parrish",
        "The_Motivation_Myth": "Jeff Haden",
        "Ultralearning": "Scott H. Young",
        "The_Happiness_Trap": "Russ Harris",
        "The_Courage_to_Be_Happy": "Ichiro Kishimi & Fumitake Koga",
        "The_Art_of_the_Good_Life": "Rolf Dobelli",
        "The_5_Elements_of_Effective_Thinking": "Edward B. Burger & Michael Starbird",
        "The_Advice_Trap": "Michael Bungay Stanier",
        "Smarter_Faster_Better": "Charles Duhigg",
        "The_Honest_Truth_About_Dishonesty": "Dan Ariely",
        "Misbehaving": "Richard Thaler",
        "The_Little_Book_That_Still_Beats_the_Market": "Joel Greenblatt",
        "One_Up_on_Wall_Street": "Peter Lynch",
        "The_Little_Book_That_Builds_Wealth": "Pat Dorsey",
        "The_Wealthy_Barber_Returns": "David Chilton",
        "Personal_Finance_for_Dummies": "Eric Tyson",
        "The_9_Steps_to_Financial_Freedom": "Suze Orman",
        "The_Power_of_Vulnerability": "Brené Brown",
        "The_ABCs_of_Real_Estate_Investing": "Ken McElroy",
        "Great_by_Choice": "Jim Collins",
        "The_Practice_of_Management": "Peter Drucker",
        "The_Four": "Scott Galloway",
        "Noise": "Daniel Kahneman",
        "The_E-Myth_Manager": "Michael Gerber",
        "Smart_Women_Finish_Rich": "David Bach",
        "It_Doesn't_Have_to_Be_Crazy_at_Work": "Jason Fried",
        # --- batch-added 2026-08-22 ---
        "The_Prince": "Niccolò Machiavelli",
        "The_Art_of_Happiness": "Dalai Lama & Howard Cutler",
        "Creative_Confidence": "Tom Kelley & David Kelley",
        "The_Bomber_Mafia": "Malcolm Gladwell",
        "What_the_Dog_Saw": "Malcolm Gladwell",
        "Get_Good_with_Money": "Tiffany Aliche",
        "How_the_Mighty_Fall": "Jim Collins",
        "How_Will_You_Measure_Your_Life": "Clayton M. Christensen",
        "Atlas_of_the_Heart": "Brené Brown",
        "Option_B": "Sheryl Sandberg & Adam Grant",
        "Discipline_Is_Destiny": "Ryan Holiday",
        "The_Fifth_Risk": "Michael Lewis",
        "Going_Infinite": "Michael Lewis",
        "The_Greatness_Guide": "Robin Sharma",
        "Dollars_and_Sense": "Dan Ariely",
        "StrengthsFinder_2.0": "Tom Rath",
        "First_Break_All_the_Rules": "Marcus Buckingham & Curt Coffman",
        "Turning_Pro": "Steven Pressfield",
        "Choose_Yourself": "James Altucher",
        "The_Art_of_Non-Conformity": "Chris Guillebeau",
    }
    fn = title.replace(" ", "_")
    if fn not in m:
        m[fn] = author
        # rewrite this function's map by patching the source (simple, local)
        src = Path(__file__).read_text()
        src = src.replace(
            '        "The_Millionaire_Next_Door": "Thomas J. Stanley",\n',
            f'        "The_Millionaire_Next_Door": "Thomas J. Stanley",\n        "{fn}": "{author}",\n')
        Path(__file__).write_text(src)


if __name__ == "__main__":
    main()
