#!/usr/bin/env python3
"""Add a new book to the Prosora blog.

Generates the PDF (if missing) and (re)builds the book DATA arrays in
index.html and books.html from the local pdf/ folder, so pagination and
"first 6 on home" stay correct automatically. No hardcoded cards.

Usage:
  python3 add_book.py "The Psychology of Money" "Morgan Housel"
"""
import sys, subprocess, re
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
VENV = BASE / ".venv" / "bin" / "activate"


def _books():
    """Scan pdf/ for book PDFs, return list of (title, author, file)."""
    out = []
    for pdf in sorted(BASE.glob("pdf/*.pdf")):
        fn = pdf.stem  # e.g. The_4-Hour_Workweek
        # find author: best-effort from known mapping; fallback blank
        out.append(fn)
    return out


def _author_for(title):
    # simple known-author map (extend as needed)
    m = {
        "Atomic_Habits": "James Clear",
        "The_Psychology_of_Money": "Morgan Housel",
        "Rich_Dad_Poor_Dad": "Robert Kiyosaki",
        "The_4-Hour_Workweek": "Timothy Ferriss",
        "The_Simple_Path_to_Wealth": "JL Collins",
        "The_Psychology_of_Human_Misjudgment": "Charlie Munger",
        "The_E-Myth_Revisited": "Michael Gerber",
        "The_Total_Money_Makeover": "Dave Ramsey",
        "Think_and_Grow_Rich": "Napoleon Hill",
        "The_Millionaire_Next_Door": "Thomas J. Stanley",
        "The_Geometry_of_Wealth": "Brian Portnoy",
        "The_Laws_of_Wealth": "Daniel Crosby",
        "Liar's_Poker": "Michael Lewis",
        "The_Big_Short": "Michael Lewis",
        "The_Investment_Answer": "Gordon Murray",
        "The_Behavior_Gap": "Carl Richards",
        "The_Little_Book_of_Behavioral_Investing": "James Montier",
        "The_Code_of_the_Extraordinary_Mind": "Vishen Lakhiani",
        "Everything_Is_F*cked": "Mark Manson",
        "What_Works_on_Wall_Street": "James O'Shaughnessy",
        "The_Index_Card": "Helaine Olen",
        "The_Algebra_of_Happiness": "Scott Galloway",
        "Money:_The_True_Story_of_a_Made-Up_Thing": "Jacob Goldstein",
        "The_Hour_Between_Dog_and_Wolf": "John Coates",
        "The_Behavioral_Investor": "Daniel Crosby",
        "Originals": "Adam Grant",
        "Show_Your_Work!": "Austin Kleon",
        "Crossing_the_Chasm": "Geoffrey A. Moore",
        "The_Subtle_Art_of_Not_Giving_a_F*ck": "Mark Manson",
        "The_Culture_Code": "Daniel Coyle",
        "The_Checklist_Manifesto": "Atul Gawande",
        "Steal_Like_an_Artist": "Austin Kleon",
        "Never_Split_the_Difference": "Chris Voss",
        "Skin_in_the_Game": "Nassim Nicholas Taleb",
        "The_Happiness_Hypothesis": "Jonathan Haidt",
        "Give_and_Take": "Adam Grant",
        "Think_Again": "Adam Grant",
        "The_Monk_Who_Sold_His_Ferrari": "Robin Sharma",
        "The_5_AM_Club": "Robin Sharma",
        "Common_Stocks_and_Uncommon_Profits": "Philip A. Fisher",
        "Value_Investing": "Bruce Greenwald",
        "The_Acquirer's_Multiple": "Tobias Carlisle",
        "The_Only_Investment_Guide_You'll_Ever_Need": "Andrew Tobias",
        "The_Bogleheads'_Guide_to_Retirement_Planning": "Taylor Larimore",
        "The_Intelligent_Asset_Allocator": "William J. Bernstein",
        "You_Can_Be_a_Stock_Market_Genius": "Joel Greenblatt",
        "Margin_of_Safety": "Seth Klarman",
        "The_Snowball": "Alice Schroeder",
        "The_Warren_Buffett_Way": "Robert Hagstrom",
        "Tribes": "Seth Godin",
        "Positioning": "Al Ries",
        "The_22_Immutable_Laws_of_Marketing": "Al Ries",
        "A_New_Earth": "Eckhart Tolle",
        "Purple_Cow": "Seth Godin",
        "The_Effective_Executive": "Peter Drucker",
        "The_Art_of_War": "Sun Tzu",
        "The_Law_of_Success": "Napoleon Hill",
        "The_First_90_Days": "Michael Watkins",
        "Crucial_Conversations": "Kerry Patterson",
        "The_4_Disciplines_of_Execution": "Chris McChesney",
        "Rich_Dad's_Guide_to_Investing": "Robert Kiyosaki",
        "Letters_from_a_Stoic": "Seneca",
        "Meditations": "Marcus Aurelius",
        "The_Art_of_Worldly_Wisdom": "Baltasar Gracian",
        "Pre-Suasion": "Robert Cialdini",
        "Contagious": "Jonah Berger",
        "Getting_Things_Done": "David Allen",
        "The_Power_of_Now": "Eckhart Tolle",
        "As_a_Man_Thinketh": "James Allen",
        "When": "Daniel H. Pink",
        "The_Art_of_Seduction": "Robert Greene",
        "David_and_Goliath": "Malcolm Gladwell",
        "Predictably_Irrational": "Dan Ariely",
        "Made_to_Stick": "Chip Heath",
        "Hooked": "Nir Eyal",
        "Measure_What_Matters": "John Doerr",
        "The_Innovator's_Dilemma": "Clayton M. Christensen",
        "So_Good_They_Can't_Ignore_You": "Cal Newport",
        "Range": "David Epstein",
        "Peak": "Anders Ericsson",
        "Influence": "Robert B. Cialdini",
        "The_Untethered_Soul": "Michael A. Singer",
        "Mindset": "Carol S. Dweck",
        "Common_Sense_on_Mutual_Funds": "John C. Bogle",
        "Stocks_for_the_Long_Run": "Jeremy J. Siegel",
        "The_Dhandho_Investor": "Mohnish Pabrai",
        "Security_Analysis": "Benjamin Graham",
        "The_Four_Pillars_of_Investing": "William J. Bernstein",
        "Nudge": "Richard H. Thaler",
        "How_to_Decide": "Annie Duke",
        "A_Mind_for_Numbers": "Barbara Oakley",
        "Digital_Minimalism": "Cal Newport",
        "The_One_Thing": "Gary Keller",
        "The_Mountain_Is_You": "Brianna Wiest",
        "The_Daily_Laws": "Robert Greene",
        "The_33_Strategies_of_War": "Robert Greene",
        "The_48_Laws_of_Power": "Robert Greene",
        "The_Dichotomy_of_Leadership": "Jocko Willink",
        "Leaders_Eat_Last": "Simon Sinek",
        "The_Infinite_Game": "Simon Sinek",
        "Start_with_Why": "Simon Sinek",
        "Drive": "Daniel Pink",
        "The_Tipping_Point": "Malcolm Gladwell",
        "Blink": "Malcolm Gladwell",
        "Outliers": "Malcolm Gladwell",
        "Grit": "Angela Duckworth",
        "Daring_Greatly": "Brené Brown",
        "The_Courage_to_Be_Disliked": "Ichiro Kishimi & Fumitake Koga",
        "The_4-Hour_Body": "Tim Ferriss",
        "Rich_Dad's_Increase_Your_Financial_IQ": "Robert Kiyosaki",
        "The_Bogleheads'_Guide_to_Investing": "Taylor Larimore",
        "Set_for_Life": "Scott Trench",
        "The_Book_on_Rental_Property_Investing": "Brandon Turner",
        "Linchpin": "Seth Godin",
        "The_Dip": "Seth Godin",
        "The_War_of_Art": "Steven Pressfield",
        "Stillness_Is_the_Key": "Ryan Holiday",
        "The_Daily_Stoic": "Ryan Holiday",
        "Models": "Mark Manson",
        "Extreme_Ownership": "Jocko Willink",
        "Discipline_Equals_Freedom": "Jocko Willink",
        "Can't_Hurt_Me": "David Goggins",
        "The_5_Second_Rule": "Mel Robbins",
        "High_Performance_Habits": "Brendon Burchard",
        "The_10X_Rule": "Grant Cardone",
        "Unlimited_Power": "Tony Robbins",
        "The_One_Minute_Millionaire": "Mark Victor Hansen",
        "Secrets_of_the_Millionaire_Mind": "T. Harv Eker",
        "The_Most_Important_Thing": "Howard Marks",
        "Poor_Charlie's_Almanack": "Charlie Munger",
        "The_Essays_of_Warren_Buffett": "Warren Buffett",
        "The_Wealthy_Barber": "David Chilton",
        "Tools_of_Titans": "Tim Ferriss",
        "How_to_Win_Friends_and_Influence_People": "Dale Carnegie",
        "Essentialism": "Greg McKeown",
        "Awaken_the_Giant_Within": "Tony Robbins",
        "Built_to_Last": "Jim Collins",
        "Shoe_Dog": "Phil Knight",
        "The_Hard_Thing_About_Hard_Things": "Ben Horowitz",
        "The_Personal_MBA": "Josh Kaufman",
        "Profit_First": "Mike Michalowicz",
        "The_Science_of_Getting_Rich": "Wallace D. Wattles",
        "You_Are_a_Badass_at_Making_Money": "Jen Sincero",
        "The_Miracle_Morning": "Hal Elrod",
        "The_Slight_Edge": "Jeff Olson",
        "Mastery": "Robert Greene",
        "The_Laws_of_Human_Nature": "Robert Greene",
        "Principles": "Ray Dalio",
        "Zero_to_One": "Peter Thiel",
        "The_$100_Startup": "Chris Guillebeau",
        "The_Power_of_Habit": "Charles Duhigg",
        "The_7_Habits_of_Highly_Effective_People": "Stephen R. Covey",
        "Deep_Work": "Cal Newport",
        "Ego_Is_the_Enemy": "Ryan Holiday",
        "The_Obstacle_Is_the_Way": "Ryan Holiday",
        "The_Almanack_of_Naval_Ravikant": "Eric Jorgenson",
        "The_Art_of_Thinking_Clearly": "Rolf Dobelli",
        "Thinking,_Fast_and_Slow": "Daniel Kahneman",
        "Antifragile": "Nassim Nicholas Taleb",
        "Fooled_by_Randomness": "Nassim Nicholas Taleb",
        "The_Black_Swan": "Nassim Nicholas Taleb",
        "The_Little_Book_That_Beats_the_Market": "Joel Greenblatt",
        "One_Up_On_Wall_Street": "Peter Lynch",
        "A_Random_Walk_Down_Wall_Street": "Burton G. Malkiel",
        "The_Barefoot_Investor": "Scott Pape",
        "Money:_Master_the_Game": "Tony Robbins",
        "The_Millionaire_Mind": "Thomas J. Stanley",
        "The_Automatic_Millionaire": "David Bach",
        "Psycho-Cybernetics": "Maxwell Maltz",
        "The_Bitcoin_Standard": "Saifedean Ammous",
        "Rich_Dad's_Cashflow_Quadrant": "Robert Kiyosaki",
        "The_Magic_of_Thinking_Big": "David J. Schwartz",
        "Unshakeable": "Tony Robbins",
        "The_Millionaire_Fastlane": "M.J. DeMarco",
        "I_Will_Teach_You_To_Be_Rich": "Ramit Sethi",
        "The_Compound_Effect": "Darren Hardy",
        "The_Richest_Man_in_Babylon": "George S. Clason",
        "Your_Money_or_Your_Life": "Vicki Robin",
        "The_Little_Book_of_Common_Sense_Investing": "John C. Bogle",
        "The_Intelligent_Investor": "Benjamin Graham",
        "The_Lean_Startup": "Eric Ries",
        "Good_to_Great": "Jim Collins",
    }
    return m.get(title, "")


def _data_js():
    lines = []
    for fn in _books():
        t = fn.replace("_", " ")
        a = _author_for(fn)
        lines.append(f'  {{t:"{t}", a:"{a}", f:"{fn}"}},')
    return "\n".join(lines)


def main():
    if len(sys.argv) >= 3:
        title, author = sys.argv[1], sys.argv[2]
        # 1. generate PDF if missing
        fn = title.replace(" ", "_")
        pdf = BASE / "pdf" / f"{fn}.pdf"
        if not pdf.exists():
            subprocess.run(f"bash -c 'source {VENV} && python3 scripts/gen_pdf.py \"{title}\" \"{author}\"'",
                           shell=True, cwd=str(BASE))
            if not pdf.exists():
                print("PDF gen failed"); sys.exit(1)
        # remember author for future scans
        _remembrance(title, author)
    # 2. rebuild data arrays in both pages
    data = _data_js()
    for page in ("index.html", "books.html"):
        p = BASE / page
        html = p.read_text()
        import re
        html = re.sub(r"<!-- BOOKS_DATA -->.*?<!-- /BOOKS_DATA -->",
                       f"<!-- BOOKS_DATA -->\n{data}\n  <!-- /BOOKS_DATA -->", html, flags=re.DOTALL)
        p.write_text(html)
    print(f"[site] rebuilt book data: {len(_books())} books in {', '.join(_books()[:3])}...")


def _remembrance(title, author):
    """Store author mapping persistently (used by _author_for)."""
    m = {
        "Atomic_Habits": "James Clear",
        "The_Psychology_of_Money": "Morgan Housel",
        "Rich_Dad_Poor_Dad": "Robert Kiyosaki",
        "The_4-Hour_Workweek": "Timothy Ferriss",
        "The_Simple_Path_to_Wealth": "JL Collins",
        "The_Psychology_of_Human_Misjudgment": "Charlie Munger",
        "The_E-Myth_Revisited": "Michael Gerber",
        "The_Total_Money_Makeover": "Dave Ramsey",
        "Think_and_Grow_Rich": "Napoleon Hill",
        "The_Millionaire_Next_Door": "Thomas J. Stanley",
        "The_Geometry_of_Wealth": "Brian Portnoy",
        "The_Laws_of_Wealth": "Daniel Crosby",
        "Liar's_Poker": "Michael Lewis",
        "The_Big_Short": "Michael Lewis",
        "The_Investment_Answer": "Gordon Murray",
        "The_Behavior_Gap": "Carl Richards",
        "The_Little_Book_of_Behavioral_Investing": "James Montier",
        "The_Code_of_the_Extraordinary_Mind": "Vishen Lakhiani",
        "Everything_Is_F*cked": "Mark Manson",
        "What_Works_on_Wall_Street": "James O'Shaughnessy",
        "The_Index_Card": "Helaine Olen",
        "The_Algebra_of_Happiness": "Scott Galloway",
        "Money:_The_True_Story_of_a_Made-Up_Thing": "Jacob Goldstein",
        "The_Hour_Between_Dog_and_Wolf": "John Coates",
        "The_Behavioral_Investor": "Daniel Crosby",
        "Originals": "Adam Grant",
        "Show_Your_Work!": "Austin Kleon",
        "Crossing_the_Chasm": "Geoffrey A. Moore",
        "The_Subtle_Art_of_Not_Giving_a_F*ck": "Mark Manson",
        "The_Culture_Code": "Daniel Coyle",
        "The_Checklist_Manifesto": "Atul Gawande",
        "Steal_Like_an_Artist": "Austin Kleon",
        "Never_Split_the_Difference": "Chris Voss",
        "Skin_in_the_Game": "Nassim Nicholas Taleb",
        "The_Happiness_Hypothesis": "Jonathan Haidt",
        "Give_and_Take": "Adam Grant",
        "Think_Again": "Adam Grant",
        "The_Monk_Who_Sold_His_Ferrari": "Robin Sharma",
        "The_5_AM_Club": "Robin Sharma",
        "Common_Stocks_and_Uncommon_Profits": "Philip A. Fisher",
        "Value_Investing": "Bruce Greenwald",
        "The_Acquirer's_Multiple": "Tobias Carlisle",
        "The_Only_Investment_Guide_You'll_Ever_Need": "Andrew Tobias",
        "The_Bogleheads'_Guide_to_Retirement_Planning": "Taylor Larimore",
        "The_Intelligent_Asset_Allocator": "William J. Bernstein",
        "You_Can_Be_a_Stock_Market_Genius": "Joel Greenblatt",
        "Margin_of_Safety": "Seth Klarman",
        "The_Snowball": "Alice Schroeder",
        "The_Warren_Buffett_Way": "Robert Hagstrom",
        "Tribes": "Seth Godin",
        "Positioning": "Al Ries",
        "The_22_Immutable_Laws_of_Marketing": "Al Ries",
        "A_New_Earth": "Eckhart Tolle",
        "Purple_Cow": "Seth Godin",
        "The_Effective_Executive": "Peter Drucker",
        "The_Art_of_War": "Sun Tzu",
        "The_Law_of_Success": "Napoleon Hill",
        "The_First_90_Days": "Michael Watkins",
        "Crucial_Conversations": "Kerry Patterson",
        "The_4_Disciplines_of_Execution": "Chris McChesney",
        "Rich_Dad's_Guide_to_Investing": "Robert Kiyosaki",
        "Letters_from_a_Stoic": "Seneca",
        "Meditations": "Marcus Aurelius",
        "The_Art_of_Worldly_Wisdom": "Baltasar Gracian",
        "Pre-Suasion": "Robert Cialdini",
        "Contagious": "Jonah Berger",
        "Getting_Things_Done": "David Allen",
        "The_Power_of_Now": "Eckhart Tolle",
        "As_a_Man_Thinketh": "James Allen",
        "When": "Daniel H. Pink",
        "The_Art_of_Seduction": "Robert Greene",
        "David_and_Goliath": "Malcolm Gladwell",
        "Predictably_Irrational": "Dan Ariely",
        "Made_to_Stick": "Chip Heath",
        "Hooked": "Nir Eyal",
        "Measure_What_Matters": "John Doerr",
        "The_Innovator's_Dilemma": "Clayton M. Christensen",
        "So_Good_They_Can't_Ignore_You": "Cal Newport",
        "Range": "David Epstein",
        "Peak": "Anders Ericsson",
        "Influence": "Robert B. Cialdini",
        "The_Untethered_Soul": "Michael A. Singer",
        "Mindset": "Carol S. Dweck",
        "Common_Sense_on_Mutual_Funds": "John C. Bogle",
        "Stocks_for_the_Long_Run": "Jeremy J. Siegel",
        "The_Dhandho_Investor": "Mohnish Pabrai",
        "Security_Analysis": "Benjamin Graham",
        "The_Four_Pillars_of_Investing": "William J. Bernstein",
        "Nudge": "Richard H. Thaler",
        "How_to_Decide": "Annie Duke",
        "A_Mind_for_Numbers": "Barbara Oakley",
        "Digital_Minimalism": "Cal Newport",
        "The_One_Thing": "Gary Keller",
        "The_Mountain_Is_You": "Brianna Wiest",
        "The_Daily_Laws": "Robert Greene",
        "The_33_Strategies_of_War": "Robert Greene",
        "The_48_Laws_of_Power": "Robert Greene",
        "The_Dichotomy_of_Leadership": "Jocko Willink",
        "Leaders_Eat_Last": "Simon Sinek",
        "The_Infinite_Game": "Simon Sinek",
        "Start_with_Why": "Simon Sinek",
        "Drive": "Daniel Pink",
        "The_Tipping_Point": "Malcolm Gladwell",
        "Blink": "Malcolm Gladwell",
        "Outliers": "Malcolm Gladwell",
        "Grit": "Angela Duckworth",
        "Daring_Greatly": "Brené Brown",
        "The_Courage_to_Be_Disliked": "Ichiro Kishimi & Fumitake Koga",
        "The_4-Hour_Body": "Tim Ferriss",
        "Rich_Dad's_Increase_Your_Financial_IQ": "Robert Kiyosaki",
        "The_Bogleheads'_Guide_to_Investing": "Taylor Larimore",
        "Set_for_Life": "Scott Trench",
        "The_Book_on_Rental_Property_Investing": "Brandon Turner",
        "Linchpin": "Seth Godin",
        "The_Dip": "Seth Godin",
        "The_War_of_Art": "Steven Pressfield",
        "Stillness_Is_the_Key": "Ryan Holiday",
        "The_Daily_Stoic": "Ryan Holiday",
        "Models": "Mark Manson",
        "Extreme_Ownership": "Jocko Willink",
        "Discipline_Equals_Freedom": "Jocko Willink",
        "Can't_Hurt_Me": "David Goggins",
        "The_5_Second_Rule": "Mel Robbins",
        "High_Performance_Habits": "Brendon Burchard",
        "The_10X_Rule": "Grant Cardone",
        "Unlimited_Power": "Tony Robbins",
        "The_One_Minute_Millionaire": "Mark Victor Hansen",
        "Secrets_of_the_Millionaire_Mind": "T. Harv Eker",
        "The_Most_Important_Thing": "Howard Marks",
        "Poor_Charlie's_Almanack": "Charlie Munger",
        "The_Essays_of_Warren_Buffett": "Warren Buffett",
        "The_Wealthy_Barber": "David Chilton",
        "Tools_of_Titans": "Tim Ferriss",
        "How_to_Win_Friends_and_Influence_People": "Dale Carnegie",
        "Essentialism": "Greg McKeown",
        "Awaken_the_Giant_Within": "Tony Robbins",
        "Built_to_Last": "Jim Collins",
        "Shoe_Dog": "Phil Knight",
        "The_Hard_Thing_About_Hard_Things": "Ben Horowitz",
        "The_Personal_MBA": "Josh Kaufman",
        "Profit_First": "Mike Michalowicz",
        "The_Science_of_Getting_Rich": "Wallace D. Wattles",
        "You_Are_a_Badass_at_Making_Money": "Jen Sincero",
        "The_Miracle_Morning": "Hal Elrod",
        "The_Slight_Edge": "Jeff Olson",
        "Mastery": "Robert Greene",
        "The_Laws_of_Human_Nature": "Robert Greene",
        "Principles": "Ray Dalio",
        "Zero_to_One": "Peter Thiel",
        "The_$100_Startup": "Chris Guillebeau",
        "The_Power_of_Habit": "Charles Duhigg",
        "The_7_Habits_of_Highly_Effective_People": "Stephen R. Covey",
        "Deep_Work": "Cal Newport",
        "Ego_Is_the_Enemy": "Ryan Holiday",
        "The_Obstacle_Is_the_Way": "Ryan Holiday",
        "The_Almanack_of_Naval_Ravikant": "Eric Jorgenson",
        "The_Art_of_Thinking_Clearly": "Rolf Dobelli",
        "Thinking,_Fast_and_Slow": "Daniel Kahneman",
        "Antifragile": "Nassim Nicholas Taleb",
        "Fooled_by_Randomness": "Nassim Nicholas Taleb",
        "The_Black_Swan": "Nassim Nicholas Taleb",
        "The_Little_Book_That_Beats_the_Market": "Joel Greenblatt",
        "One_Up_On_Wall_Street": "Peter Lynch",
        "A_Random_Walk_Down_Wall_Street": "Burton G. Malkiel",
        "The_Barefoot_Investor": "Scott Pape",
        "Money:_Master_the_Game": "Tony Robbins",
        "The_Millionaire_Mind": "Thomas J. Stanley",
        "The_Automatic_Millionaire": "David Bach",
        "Psycho-Cybernetics": "Maxwell Maltz",
        "The_Bitcoin_Standard": "Saifedean Ammous",
        "Rich_Dad's_Cashflow_Quadrant": "Robert Kiyosaki",
        "The_Magic_of_Thinking_Big": "David J. Schwartz",
        "Unshakeable": "Tony Robbins",
        "The_Millionaire_Fastlane": "M.J. DeMarco",
        "I_Will_Teach_You_To_Be_Rich": "Ramit Sethi",
        "The_Compound_Effect": "Darren Hardy",
        "The_Richest_Man_in_Babylon": "George S. Clason",
        "Your_Money_or_Your_Life": "Vicki Robin",
        "The_Little_Book_of_Common_Sense_Investing": "John C. Bogle",
        "The_Intelligent_Investor": "Benjamin Graham",
        "The_Lean_Startup": "Eric Ries",
        "Good_to_Great": "Jim Collins",
    }
    fn = title.replace(" ", "_")
    if fn not in m:
        m[fn] = author
        # rewrite this function's map by patching the source (simple, local)
        src = Path(__file__).read_text()
        src = src.replace(
            '        "The_Millionaire_Next_Door": "Thomas J. Stanley",\n',
            f'        "The_Millionaire_Next_Door": "Thomas J. Stanley",\n        "{fn}": "{author}",\n')
        Path(__file__).write_text(src)


if __name__ == "__main__":
    main()
